### ISSUE TITLE
No way to define admin IDs

### ISSUE THREAD

**Issue by dtupper** [Mephi00/v-rising-wine-docker-image#4] opened 2022-05-30 08:03 UTC
Putting an `adminlist.txt` with newline-delimited Steam64IDs into the Settings folder next to the ServerGame and ServerHostSettings.json files would assumedly allow admins to be defined, but it does not seem to respect that file.

**Comment by Mephi00** [comment] 2022-05-30 08:57
strange, in which location do you store the file?

**Comment by dtupper** [comment] 2022-05-30 10:15
In my user home dir:
```
tupper@adityas Settings $ ls
adminlist.txt  ServerGameSettings.json  ServerHostSettings.json
tupper@adityas Settings $ pwd
/home/tupper/morb/Settings
tupper@adityas Settings $ cd ..
tupper@adityas morb $ ls
Saves  Settings  v-rising-wine-docker-image
```
Could be a permissions thing but I also created ServerGame and ServerHost from my `tupper` user. All three files in Settings have identical permissions.

**Comment by Mephi00** [comment] 2022-05-30 10:32
are you mounting the settings files to /saves/Settings ?

**Comment by dtupper** [comment] 2022-05-30 23:19
I must be, because the server is respecting the settings I'm setting.

**Comment by dtupper** [comment] 2022-05-30 23:26
I just verified that the server is respecting the settings by changing the MOTD in ServerHost and restarting. `adminauth` still results in an error.

**Comment by Mephi00** [comment] 2022-05-31 19:21
Strange, according to the documentation of Stunlock Studios, the server should respect all Settings in the mount path. I will test if it needs to be saved in the default location and cannot be used by specifying the path.

**Comment by Mephi00** [comment] 2022-05-31 19:30
I want to correct myself and say, that I have misread the documentation and will add support for this behaviour in the next version.

**Comment by dtupper** [comment] 2022-06-01 02:16
Awesome! Thanks for taking a look Mephi.

**Comment by ghost** [comment] 2022-06-04 17:02
Thanks I have this issue as well and came here for this purpose. A temporary solution you can use is:
`docker exec VRISING bash -c 'echo "STEAM_ID_HERE" >> /home/steam/Steam/steamapps/common/VRisingDedicatedServer/VRisingServer_Data/StreamingAssets/Settings/adminlist.txt'`

**Comment by Mephi00** [comment] 2022-06-07 13:22
RealityWinner has the easiest workaround so far. I still want to enable this by simply using a symlink to the adminlist.txt from the Settings folder.

**Comment by saltydk** [comment] 2022-06-23 17:02
Not sure this should be closed as the current implementation just resets the file on restarts.

**Comment by Mephi00** [comment] 2022-06-28 08:47
Can you tell me more about that, I haven‘t seen this behavior in any of my tests. The script creates an empty file if the file doesn‘t exist, but won‘t overwrite it.

**Comment by saltydk** [comment] 2022-06-28 09:12
Example of it happening:
```
➜  Settings cat adminlist.txt
76561197960353982
➜  Settings docker restart v-risingtest
v-risingtest
➜  Settings cat adminlist.txt
➜  Settings
```

**Comment by saltydk** [comment] 2022-06-28 09:25
Couldn't you just copy the file to the internal directory instead when starting? I suppose the game might be overwriting the file due to it being a symlink. Since the startup actions always fire the symlink doesn't make any sense to me regardless.

**Comment by Mephi00** [comment] 2022-06-29 13:23
I wanted it to be a symlink, so you can edit the files on the fly and it works.

From my testing, the game doesn‘t overwrite the content. I didn‘t use the latest version for testing tho, maybe an update broke the functionality. I‘ll look into this further.

**Comment by saltydk** [comment] 2022-06-29 13:27
Don't you have to restart the container for it to pick up this configuration anyway?

**Comment by saltydk** [comment] 2022-06-29 13:30
A cleaner solution is probably just to symlink the relevant folders instead of dealing with the files, then you can do it in the image and not have to deal with it during runtime outside of producing the templates if they don't exist the first time around.

**Comment by saltydk** [comment] 2022-06-29 13:38
Additionally this https://github.com/StunlockStudios/vrising-dedicated-server-instructions confuses me more as it seems to suggest that the game would be loading the configuration from /saves/Settings/ by default when you change the data directory. So is the symlinking even needed?

**Comment by Mephi00** [comment] 2022-06-29 13:54
> Additionally this https://github.com/StunlockStudios/vrising-dedicated-server-instructions confuses me more as it seems to suggest that the game would be loading the configuration from /saves/Settings/ by default when you change the data directory. So is the symlinking even needed?

Yes symlinking is needed because the directory change for the settings is only applicable for the settings.json files. I was very confused about this too until I read the instructions a third time.

**Comment by saltydk** [comment] 2022-06-29 14:02
You mean not the admin and ban files?

**Comment by Mephi00** [comment] 2022-06-29 14:14
> You mean not the admin and ban files?

Exactly, was a very strange 2 evenings I spent to figure that out. 

And btw, the server reads the adminlist and banlist everytime someone tries to use adminauth or tries to connect. So it does allow you to change the admins without a restart.

**Comment by saltydk** [comment] 2022-06-29 17:19
> > You mean not the admin and ban files?
> 
> Exactly, was a very strange 2 evenings I spent to figure that out.
> 
> And btw, the server reads the adminlist and banlist everytime someone tries to use adminauth or tries to connect. So it does allow you to change the admins without a restart.

So I did a quick fork and messed about while half asleep https://github.com/saltydk/docker-v-rising and the result pretty much confirmed what I read on their instructions page. It'll load them after the default ones are loaded without any problems, so unless this is something that happened with an older build of the game then this should simplify your setup.

**Comment by saltydk** [comment] 2022-06-29 17:19
Log which shows the banlist being loaded 
```
[FileUserList] Loaded FileUserList from: Z:\home\steam\Steam\steamapps\common\VRisingDedicatedServer\VRisingServer_Data\StreamingAssets\Settings\banlist.txt, Added: 0

UnityEngine.Logger:Log(LogType, Object)

UnityEngine.Debug:Log(Object)

ProjectM.FileUserList:RefreshLocal(Boolean)

ProjectM.KickBanSystem_Server:OnUpdate()

Unity.Entities.SystemBase:Update()

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

Unity.Entities.ComponentSystem:Update()

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

ProjectM.ServerSimulationSystemGroup:OnUpdate()

Unity.Entities.ComponentSystem:Update()

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

Unity.Entities.ComponentSystem:Update()

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

Unity.Entities.ComponentSystem:Update()

UnityEngine.LowLevel.UpdateFunction:Invoke()

[FileUserList] Loaded FileUserList from: Z:\saves\Settings\banlist.txt, Added: 0
```
adminlist was tested with just authing.

**Comment by saltydk** [comment] 2022-06-29 17:23
Image is here if you want to validate it yourself. https://hub.docker.com/r/saltydk/v-rising

**Comment by Mephi00** [comment] 2022-06-30 22:03
> Log which shows the banlist being loaded
> 
> ```
> [FileUserList] Loaded FileUserList from: Z:\home\steam\Steam\steamapps\common\VRisingDedicatedServer\VRisingServer_Data\StreamingAssets\Settings\banlist.txt, Added: 0
> 
> UnityEngine.Logger:Log(LogType, Object)
> 
> UnityEngine.Debug:Log(Object)
> 
> ProjectM.FileUserList:RefreshLocal(Boolean)
> 
> ProjectM.KickBanSystem_Server:OnUpdate()
> 
> Unity.Entities.SystemBase:Update()
> 
> Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
> 
> Unity.Entities.ComponentSystem:Update()
> 
> Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
> 
> ProjectM.ServerSimulationSystemGroup:OnUpdate()
> 
> Unity.Entities.ComponentSystem:Update()
> 
> Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
> 
> Unity.Entities.ComponentSystem:Update()
> 
> Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
> 
> Unity.Entities.ComponentSystem:Update()
> 
> UnityEngine.LowLevel.UpdateFunction:Invoke()
> 
> [FileUserList] Loaded FileUserList from: Z:\saves\Settings\banlist.txt, Added: 0
> ```
> 
> adminlist was tested with just authing.

Thank you very much, I've just removed the whole symlinking thing if it just works now. I have tested it and it is working now.

**Closed as completed by Mephi00** 2022-06-30 22:03 UTC
